#!/bin/sh

set -eu

. "$(dirname -- "$0")/ai-dev-common.sh"

if [ "${1:-}" = "--" ]; then
  shift
fi

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  ai_dev_usage "prepare-cloud"
  exit 0
fi

ai_dev_parse_task_args "$@"

plan_file=$AI_DEV_WORK_DIR/plan.md
todo_file=$AI_DEV_WORK_DIR/todo.md
test_cases_file=$AI_DEV_WORK_DIR/test-cases.md
status_file=$(ai_dev_status_file)
review_self_file=$AI_DEV_WORK_DIR/review-self.md
review_external_file=$AI_DEV_WORK_DIR/review-external.md
packet_file=$(ai_dev_packet_file)
branch_name=$(git -C "$ai_dev_repo_root" rev-parse --abbrev-ref HEAD 2>/dev/null || printf 'unknown')

if [ "$AI_DEV_DRY_RUN" -eq 1 ]; then
  missing_items=""
  if [ ! -f "$plan_file" ]; then
    missing_items="${missing_items}\n- missing plan file: $plan_file"
  fi
  if [ ! -f "$todo_file" ]; then
    missing_items="${missing_items}\n- missing todo file: $todo_file"
  fi
  if [ ! -f "$test_cases_file" ]; then
    missing_items="${missing_items}\n- missing test-cases file: $test_cases_file"
  fi
  if [ ! -f "$status_file" ]; then
    missing_items="${missing_items}\n- missing status file: $status_file"
  elif ! ai_dev_status_is_c3_approved "$status_file"; then
    missing_items="${missing_items}\n- missing C-3 approval marker in $status_file"
  fi

  printf 'Would generate:\n- %s\n\nFrom:\n- %s\n- %s\n- %s\n- %s\n- %s (if present)\n- %s (if present)\n' \
    "$packet_file" \
    "$plan_file" \
    "$todo_file" \
    "$test_cases_file" \
    "$status_file" \
    "$review_self_file" \
    "$review_external_file"
  if [ -n "$missing_items" ]; then
    printf 'Preconditions not yet satisfied:%b\n' "$missing_items"
  else
    echo "Preconditions satisfied."
  fi
  exit 0
fi

ai_dev_ensure_work_dir

ai_dev_require_file "$plan_file" "plan file"
ai_dev_require_file "$todo_file" "todo file"
ai_dev_require_file "$test_cases_file" "test-cases file"
ai_dev_require_file "$status_file" "status file"
ai_dev_require_status_c3_approved "$status_file"

previous_packet_file=""
if [ -f "$packet_file" ] && [ "$(ai_dev_packet_task_id "$packet_file" 2>/dev/null || true)" = "$AI_DEV_TASK" ]; then
  previous_packet_file=$packet_file
fi

approved_scope_content=$(ai_dev_get_markdown_section_or_default "$previous_packet_file" "Approved Scope" "- TODO: 人間が承認したスコープをここに要約する")
open_questions_content=$(ai_dev_get_markdown_section_or_default "$previous_packet_file" "Open Questions / Non-Goals" "- TODO")
verification_policy_content=$(ai_dev_get_markdown_section_or_default "$previous_packet_file" "Verification Policy" "- During implementation, prioritize tests and checks for the modified area.
- Record commands and results in this packet.
- End by requesting human approval for final completion.")
approval_request_note_content=$(ai_dev_get_markdown_section_or_default "$previous_packet_file" "Approval Request Note" "- TODO: Cloud task 完了後に人間へ渡す要約をここに追記する")

cat >"$packet_file" <<EOF
# Codex Cloud Manual Task Handoff

> Generated by: \`./scripts/ai-dev-workflow $AI_DEV_TASK prepare-cloud\`
> Generated at: $(ai_dev_today)
> Source directory: \`docs/working/$AI_DEV_TASK/\`

このファイルは、Codex Cloud の手動 task 起動時に使う tracked handoff packet です。
通常の実作業チケットに使う \`docs/working/\` 配下のファイルは gitignored のため、Cloud task から直接読める前提にしません。

## 使い方

1. 人間が C-3 承認状態を確認する
2. 必要なら承認済みスコープと未解決事項をこのファイル上で微調整する
3. Cloud task 起動時は、このファイルを最初に読む
4. Cloud task はこのファイルに書かれた内容だけを作業指示として扱う

## Task

- Task ID: $AI_DEV_TASK
- Branch name: $branch_name
- C-3 approval: approved
- Final completion owner: human

## Approved Scope
EOF

printf '%s\n\n' "$approved_scope_content" >>"$packet_file"

cat >>"$packet_file" <<'EOF'

## Constraints

- Do not expand scope without user approval.
- Prioritize targeted test / lint / typecheck for the modified area during Cloud execution.
- Treat Cloud task completion as provisional until human approval is requested.
- Update this packet with progress, verification evidence, and approval request notes.
EOF

ai_dev_append_markdown_file_section "$packet_file" "Approved Plan" "$plan_file"
ai_dev_append_markdown_file_section "$packet_file" "Todo" "$todo_file"
ai_dev_append_markdown_file_section "$packet_file" "Test Cases" "$test_cases_file"
ai_dev_append_markdown_file_section "$packet_file" "Status Notes" "$status_file"

if [ -f "$review_self_file" ]; then
  ai_dev_append_markdown_file_section "$packet_file" "Self Review" "$review_self_file"
fi

if [ -f "$review_external_file" ]; then
  ai_dev_append_markdown_file_section "$packet_file" "External Review" "$review_external_file"
fi

cat >>"$packet_file" <<'EOF'

## Open Questions / Non-Goals

EOF

printf '%s\n\n' "$open_questions_content" >>"$packet_file"

cat >>"$packet_file" <<'EOF'

## Verification Policy
EOF

printf '%s\n\n' "$verification_policy_content" >>"$packet_file"

cat >>"$packet_file" <<'EOF'

## Approval Request Note
EOF

printf '%s\n\n' "$approval_request_note_content" >>"$packet_file"

cat >>"$packet_file" <<'EOF'

## Startup Template

```text
Read .codex/manual-cloud-task.md first.
Execute only the approved scope described here.
Do not assume docs/working ticket files are directly visible.
If the handoff packet is missing information, stop and ask a question.
Update only the files listed in the handoff packet.
Prioritize tests and checks for the modified area during implementation.
Treat task completion as provisional until human approval is requested.
Return a concise summary with changed files, targeted verification results, and the approval request note.
```
EOF

echo "Updated handoff packet: $packet_file"
